### PR TITLE
Toolbox Version 2.0 - Update all contents

### PR DESCRIPTION
**Pull request by adisadit**
Hi @dakotabenjamin I test a pull request for updating content for chapter 1. Please check if this correct or not (I create a branch called new-content)

### CODE REVIEW

**Comment by adisadit** [comment]
Added chapter 2 and 3 as well

**Comment by dakotabenjamin** [comment]
I noticed different naming schema for files, is that intentional? lots of changes here I will have to take some time to review

**Comment by adisadit** [comment]
> I noticed different naming schema for files, is that intentional? lots of changes here I will have to take some time to review

Yes that's intentional. Previous naming (especially for images) is confusing. I put renamed it into different section just like what I did back then in the pdc-documentation.

 Should I pause my push until you check it?

**Comment by dakotabenjamin** [comment]
Let me know when the changes are complete and I will review the whole set of changes together. You can set the PR as WIP until it's ready for merge

**Review by dakotabenjamin — APPROVED** [review]

**Pull request merged**
